/******************** TABLES **********************/
RECREATE TABLE SCHED_ITEMS
(
  ID Integer NOT NULL,
  LESSON_ID Integer,
  SUBJECT_ID Integer,
  AUDIENCE_ID Integer,
  GROUP_ID Integer,
  TEACHER_ID Integer,
  TYPE_ID Integer,
  WEEKDAY_ID Integer,
  PRIMARY KEY (ID)
);

RECREATE TABLE AUDIENCES
(
  ID Integer NOT NULL,
  NAME Varchar(64),
  PRIMARY KEY (ID)
);

RECREATE TABLE SUBJECT_GROUP
(
  ID Integer NOT NULL,
  SUBJECT_ID Integer NOT NULL,
  GROUP_ID Integer NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UNIQ_SUBJECTID_GROUPID UNIQUE (SUBJECT_ID,GROUP_ID)
);

RECREATE TABLE GROUPS
(
  ID Integer NOT NULL,
  NAME Varchar(64),
  PRIMARY KEY (ID)
);

RECREATE TABLE LESSONS
(
  ID Integer NOT NULL,
  NAME Varchar(255),
  ORDER_NUMBER Integer,
  PRIMARY KEY (ID),
  CONSTRAINT UNIQ_LESSON_ORDER UNIQUE (ORDER_NUMBER)
);

RECREATE TABLE LESSON_TYPES
(
  ID Integer NOT NULL,
  NAME Varchar(255),
  PRIMARY KEY (ID)
);


RECREATE TABLE SUBJECT_TEACHER
(
  ID Integer NOT NULL,
  SUBJECT_ID Integer NOT NULL,
  TEACHER_ID Integer NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UNIQ_SUBJECTID_TEACHERID UNIQUE (SUBJECT_ID,TEACHER_ID)
);

RECREATE TABLE SUBJECTS
(
  ID Integer NOT NULL,
  NAME Varchar(255),
  PRIMARY KEY (ID)
);


RECREATE TABLE TEACHERS
(
  ID Integer NOT NULL,
  NAME Varchar(255),
  PRIMARY KEY (ID)
);

RECREATE TABLE WEEKDAYS
(
  ID Integer NOT NULL,
  NAME Varchar(64) NOT NULL,
  ORDER_NUMBER Integer NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (ORDER_NUMBER)
);

COMMIT WORK;

/******************* CONSTRAINTS  *******************/

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_1
  FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_2
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_3
  FOREIGN KEY (AUDIENCE_ID) REFERENCES AUDIENCES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_4
  FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_5
  FOREIGN KEY (TYPE_ID) REFERENCES LESSON_TYPES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_6
  FOREIGN KEY (WEEKDAY_ID) REFERENCES WEEKDAYS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_7
  FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);

ALTER TABLE SUBJECT_GROUP ADD
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_GROUP ADD
  FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SUBJECT_TEACHER ADD
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_TEACHER ADD
  FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);

-- COMMIT WORK;

/****************** GENERATORS ********************/

RECREATE GENERATOR AUDIENCES_GEN
  START WITH 0;
RECREATE GENERATOR WEEKDAYS_GEN
  START WITH 0;
RECREATE GENERATOR SUBJECT_GROUP_GEN
  START WITH 0;
RECREATE GENERATOR GROUPS_GEN
  START WITH 0;
RECREATE GENERATOR LESSONS_GEN
  START WITH 0;
RECREATE GENERATOR LESSON_TYPES_GEN
  START WITH 0;
RECREATE GENERATOR SCHED_ITEMS_GEN
  START WITH 0;
RECREATE GENERATOR SUBJECTS_GEN
  START WITH 0;
RECREATE GENERATOR TEACHERS_GEN
  START WITH 0;
RECREATE GENERATOR SUBJECT_TEACHER_GEN
  START WITH 0;


/******************** TRIGGERS ********************/

SET TERM ^ ;
RECREATE TRIGGER AUDIENCES_AUTOINC_ID FOR AUDIENCES ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (AUDIENCES_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER WEEKDAYS_AUTOINC_ID FOR WEEKDAYS ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (WEEKDAYS_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER SUBJECT_GROUP_AUTOINC_ID FOR SUBJECT_GROUP ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (SUBJECT_GROUP_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER SUBJECT_TEACHER_AUTOINC_ID FOR SUBJECT_TEACHER ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (SUBJECT_TEACHER_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER GROUPS_AUTOINC_ID FOR GROUPS ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (GROUPS_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER LESSONS_AUTOINC_ID FOR LESSONS ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSONS_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER LESSON_TYPES_AUTOINC_ID FOR LESSON_TYPES ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSON_TYPES_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER SCHED_ITEMS_AUTOINC_ID FOR SCHED_ITEMS ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(SCHED_ITEMS_GEN, 1);
END^
SET TERM ; ^

SET TERM ^ ;
RECREATE TRIGGER SUBJECTS_AUTOINC_ID FOR SUBJECTS ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(subjects_gen, 1);
END^
SET TERM ; ^

SET TERM ^ ;

RECREATE TRIGGER TEACHERS_AUTOINC_ID FOR TEACHERS ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (TEACHERS_GEN, 1);
END^
SET TERM ; ^

COMMIT WORK;
/******************* DATA  *******************/

/******************* AUDIENCES  *******************/

INSERT INTO AUDIENCES (ID,NAME) values (null, 'D549a');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D732');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D547');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D548');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D549');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D743');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D412/542');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D945');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D741');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D654/752');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D818');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D738');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D733a');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'S');
INSERT INTO AUDIENCES (ID,NAME) values (null, 'D949');

/******************* WEEKDAYS  *******************/

INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (null, 'понедельник', 0);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (null, 'вторник', 1);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (null, 'среда', 2);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (null, 'четверг', 3);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (null, 'пятница', 4);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (null, 'суббота', 5);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (null, 'воскресенье', 6);

/******************* GROUPS  *******************/

INSERT INTO GROUPS (ID,NAME) values (null, 'Б8203а');
INSERT INTO GROUPS (ID,NAME) values (null, 'Б8203б');

/******************* LESSONS  *******************/

INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (null, '1 пара', 1);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (null, '2 пара', 2);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (null, '3 пара', 3);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (null, '4 пара', 4);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (null, '5 пара', 5);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (null, '6 пара', 6);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (null, '7 пара', 7);

/******************* LESSON_TYPES  *******************/

INSERT INTO LESSON_TYPES (ID,NAME) values (null, 'ПЗ');
INSERT INTO LESSON_TYPES (ID,NAME) values (null, 'Л');
INSERT INTO LESSON_TYPES (ID,NAME) values (null, 'ЛР');

/******************* SUBJECTS  *******************/

INSERT INTO SUBJECTS (ID,NAME) values (null, 'Иностранный язык');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Дискретная математика и математическая логика');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Архитектура компьютеров');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Математический анализ');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Основы современных образовательных технологий');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Обыкновенные дифференциальные уравнения');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Элективные курсы по физической культуре');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Численные методы');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Базы данных');
INSERT INTO SUBJECTS (ID,NAME) values (null, 'Теория вероятностей и математическая статистика');

/******************* SUBJECT_GROUP  *******************/

INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 1, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 1, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 2, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 2, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 3, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 3, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 4, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 4, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 5, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 5, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 6, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 6, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 7, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 7, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 8, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 8, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 9, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 9, 2);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 10, 1);
INSERT INTO SUBJECT_GROUP (ID,SUBJECT_ID,GROUP_ID) values (null, 10, 2);

/******************* TEACHERS  *******************/

INSERT INTO TEACHERS (ID,NAME) values (null, 'Василенко Н.Ю.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Баранов А.А.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Шепелева Р.П.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Клевчихин Ю.А.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Колобов А.Г.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Кузнецова Н.В.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Лиховидов В.Н.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Кленин А.С.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Ефремов Е.Л.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Колосова В.Е.');
INSERT INTO TEACHERS (ID,NAME) values (null, 'Веремеева Ирина Феликсовна');

/******************* SUBJECT_TEACHER  *******************/

INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 2, 1);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 3, 2);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 3, 8);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 4, 4);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 4, 9);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 5, 10);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 6, 3);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 8, 5);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 8, 6);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 9, 8);
INSERT INTO SUBJECT_TEACHER (ID,SUBJECT_ID,TEACHER_ID) values (null, 10, 7);

/******************* SCHED_ITEMS  *******************/

INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 1, 2, 2, 1, 1, 2, 1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 2, 1, 3, 1, NULL, 1, 1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 2, 1, 4, 1, NULL, 1, 1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 2, 1, 15, 1, NULL, 1, 1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 3, 3, 1, 1, 2, 3, 1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 4, 3, 1, 1, 2, 3, 1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 1, 8, 13, 1, 6, 3, 5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 1, 4, 6, 1, 9, 1, 2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 3, 6, 7, 1, 3, 1, 2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 2, 3, 13, 1, 2, 3, 5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 4, 6, 7, 1, 3, 2, 2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 3, 10, 9, 1, 7, 1, 5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 5, 7, 14, 1, NULL, 1, 2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 4, 10, 9, 1, 7, 2, 5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 5, 7, 14, 1, NULL, 1, 5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 2, 2, 8, 1, 1, 1, 3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 3, 4, 7, 1, 4, 2, 3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 4, 3, 12, 1, 8, 2, 3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 5, 8, 10, 1, 5, 2, 3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 1, 9, 5, 1, 8, 3, 4);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 2, 9, 5, 1, 8, 3, 4);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (null, 3, 9, 11, 1, 8, 2, 4);